//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Steam
{
    public static partial class Networking
    {
        /// <summary>
        /// Steam universes.  Each universe is a self-contained Steam instance.
        /// </summary>
        public enum EUniverse : int
        {
            Euniverseinvalid = unchecked((int)0),
            
            Euniversepublic = unchecked((int)1),
            
            Euniversebeta = unchecked((int)2),
            
            Euniverseinternal = unchecked((int)3),
            
            Euniversedev = unchecked((int)4),
            
            /// <summary>
            /// k_EUniverseRC = 5,				// no such universe anymore
            /// </summary>
            Euniversemax,
        }
        
        public const Networking.EUniverse Euniverseinvalid = EUniverse.Euniverseinvalid;
        
        public const Networking.EUniverse Euniversepublic = EUniverse.Euniversepublic;
        
        public const Networking.EUniverse Euniversebeta = EUniverse.Euniversebeta;
        
        public const Networking.EUniverse Euniverseinternal = EUniverse.Euniverseinternal;
        
        public const Networking.EUniverse Euniversedev = EUniverse.Euniversedev;
        
        /// <summary>
        /// k_EUniverseRC = 5,				// no such universe anymore
        /// </summary>
        public const Networking.EUniverse Euniversemax = EUniverse.Euniversemax;
    }
}
