name: WorkFlow Tests

on: [push, pull_request]

jobs:
  WindowsTest:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Submodule init
      run: git submodule init
    - name: Submodule update
      run: git submodule update
    - name: Restore dependencies
      run: dotnet restore "RhubarbEngineTests"
    - name: Build
      run: dotnet build "RhubarbEngineTests" --no-restore /p:Configuration=Release /p:Platform="x64"
    - name: Test
      run: dotnet test "RhubarbEngineTests" --no-build --no-restore /p:Configuration=Release /p:Platform="x64" --logger "console;verbosity=detailed"

  UbuntuTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Submodule init
      run: git submodule init
    - name: Submodule update
      run: git submodule update
    - name: Restore dependencies
      run: dotnet restore "RhubarbEngineTests"
    - name: Build
      run: dotnet build "RhubarbEngineTests" --no-restore /p:Configuration=Release /p:Platform="x64"
    - name: Test
      run: dotnet test "RhubarbEngineTests" --no-build /p:Configuration=Release /p:Platform="x64" --logger "console;verbosity=detailed"

  Release:
    needs: [WindowsTest,UbuntuTest]
    runs-on: ubuntu-latest
    if: contains('refs/heads/production', github.ref)
    steps:
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
         webhook: ${{ secrets.YOUR_DISCORD_WEBHOOK_URL }}


